version: 0.1.{build}.0

os: Windows Server 2012 R2

environment:
  CoverallsRepoToken:
    secure: WXZlfaiKX3qXFJzOyTQ4qWAG+O4WGoLmBmmLUyknx1pLj7QLAah/ZR2hHdwpz/Jp

assembly_info:
  patch: true
  file: AssemblyVersion.cs
  assembly_version: "0.1.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  project: src\NuGetPackagesTidier.msbuild
  verbosity: minimal

artifacts:
  - path: src\BuildOutput\*.zip
  - path: src\TestResults\*\*.coverage

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: GitHub
    tag: "$(APPVEYOR_REPO_TAG_NAME)"
    release: "NuGetPackagesTidier $(APPVEYOR_REPO_TAG_NAME)"
    description: "$(GitHubReleaseDescription)"
    auth_token:
      secure: LUCJOEKU3XJOoQz+NYCiAQ4slrN0YFlyjg6fpVgSt/4DHdwochvHaGSW+lSFVS4D
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
